### ISSUE TITLE
"cat: /root/.xsession-errors: 没有那个文件或目录"这是为什么呢？

### ISSUE THREAD

**Issue by CCrazyPeter** [linuxdeepin/youqu#66]
root@peter-PC:/home/peter/Desktop/uos-youqu/wechat_automation_test# youqu manage.py startapp testabc
cat: /root/.xsession-errors: 没有那个文件或目录
cat: /root/.xsession-errors: 没有那个文件或目录
cat: /root/.xsession-errors: 没有那个文件或目录
cat: /root/.xsession-errors: 没有那个文件或目录
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: 无法连接：Connection refused
No protocol specified

(manage.py:29977): dbind-WARNING **: 17:19:56.171: Could not open X display

(manage.py:29977): dbind-ERROR **: 17:19:56.177: AT-SPI: Couldn't connect to accessibility bus. Is at-spi-bus-launcher running?
/usr/bin/youqu：行 1: 29977 追踪与中断点陷阱（核心已转储）pipenv run python "$@"

**Comment by mikigo** [comment]
不以root运行，直接在peter用户下运行

**Comment by CCrazyPeter** [comment]
`peter@peter-PC:~/Desktop/uos-youqu/wechat_automation_test$ sudo bash env.sh
zipp                  3.15.0
chmod: 无法访问'/usr/bin/youqu-shell-rm': 没有那个文件或目录
cat: /root/.xsession-errors: 没有那个文件或目录
cat: /root/.xsession-errors: 没有那个文件或目录
cat: /root/.xsession-errors: 没有那个文件或目录
cat: /root/.xsession-errors: 没有那个文件或目录
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: 无法连接：Connection refused
No protocol specified

(manage.py:10529): dbind-WARNING **: 09:48:52.383: Could not open X display

(manage.py:10529): dbind-ERROR **: 09:48:52.389: AT-SPI: Couldn't connect to accessibility bus. Is at-spi-bus-launcher running?
/usr/bin/youqu：行 1: 10529 追踪与中断点陷阱pipenv run python "$@"`

报以上错误，看起来像是这个文件里194行：sudo chmod +x /usr/bin/youqu-shell-rm  是不是这里的问题？

**Comment by CCrazyPeter** [comment]
安装环境依赖的时候，不加sudo，显示如下：
peter@peter-PC:~/Desktop/uos-youqu/wechat_automation_test$ bash env.sh 
bash:行1: 1：未找到命令

 ██╗   ██╗  ██████╗      ███████╗ ███╗   ██╗ ██╗   ██╗
 ╚██╗ ██╔╝ ██╔═══██╗     ██╔════╝ ████╗  ██║ ██║   ██║
  ╚████╔╝  ██║   ██║     █████╗   ██╔██╗ ██║ ██║   ██║
   ╚██╔╝   ██║▄▄ ██║     ██╔══╝   ██║╚██╗██║ ╚██╗ ██╔╝
    ██║    ╚██████╔╝     ███████╗ ██║ ╚████║  ╚████╔╝
    ╚═╝     ╚══▀▀═╝      ╚══════╝ ╚═╝  ╚═══╝   ╚═══╝
    2.6.0

命中:3 https://pro-driver-packages.uniontech.com eagle InRelease                      
命中:2 https://cdn-professional-security.chinauos.com eagle/1060 InRelease                                        
命中:1 https://professional-packages.chinauos.com/desktop-professional eagle InRelease                            
命中:4 https://professional-packages.chinauos.com/printer eagle InRelease                                         
命中:5 https://app-store-files.uniontech.com/240515173103300/appstore eagle-pro InRelease                         
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有 28 个软件包可以升级。请执行 ‘apt list --upgradable’ 来查看它们。
python3-pip     安装成功 √
python3-tk      安装成功 √
sshpass 安装成功 √
scrot   安装成功 √
openjdk-11-jdk-headless 安装成功 √
gir1.2-atspi-2.0        安装成功 √
libatk-adaptor  安装成功 √
at-spi2-core    安装成功 √
python3-opencv  安装成功 √
pipenv  安装成功 √

**WARNING: apt does not have a stable CLI interface. Use with caution in scripts.**

忽略:1 https://professional-packages.chinauos.com/desktop-professional eagle/main amd64 python3-gi amd64 3.30.4-1
错误:1 https://professional-packages.chinauos.com/desktop-professional eagle/main amd64 python3-gi amd64 3.30.4-1
  无法打开文件 /home/peter/Desktop/uos-youqu/wechat_automation_test/python3-gi_3.30.4-1_amd64.deb - open (13: 权限不够) [IP: 125.74.45.107 443]
E: 无法下载 https://cdn-professional-security.chinauos.com/pool/main/p/pygobject/python3-gi_3.30.4-1_amd64.deb  无法打开文件 /home/peter/Desktop/uos-youqu/wechat_automation_test/python3-gi_3.30.4-1_amd64.deb - open (13: 权限不够) [IP: 125.74.45.107 443]

**Comment by CCrazyPeter** [comment]
然后创建APP工程又报如下错误：
peter@peter-PC:~/Desktop/uos-youqu/wechat_automation_test$ youqu manage.py startapp wechat
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    from funnylog import logger
ModuleNotFoundError: No module named 'funnylog'

**Comment by mikigo** [comment]
进群聊

![ffe14de0-a526-4e9b-8485-c87435dbf34c](https://github.com/linuxdeepin/youqu/assets/47137003/325e9abe-fa4e-4ca2-b140-a97bb7b8d597)
